nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"

mariadb:
  image: mariadb
  volumes_from:
    - dbdata
  environment:
    MYSQL_ROOT_PASSWORD: "mypass"
    MYSQL_DATABASE: "wpdb"
#  volumes:
#    - ./data/sql:/docker-entrypoint-initdb.d #Put your sql dump file(s) in the data/sql directory and the database will be initialzed with it
  ports:
    - "3306:3306"

dbdata:  # Used to store the database files
  image: ubuntu:trusty
  volumes:
    - /var/lib/mysql
  expose:
    - "20"

wp: # the wp container
  image: ocasta/nginx-hhvm-for-wp:4.6
  environment:
    - VIRTUAL_HOST=docker.local
    - UPLOADS_DIR=/uploads
    - WP_DEBUG=True
    - KEY_OVERRIDE=True
    - DB_NAME=wpdb
    - DB_USER=root
    - DB_PASSWORD=mypass
    - DB_HOST=mariadb
    - WP_FS_METHOD=direct
    - WP_ENV=development
    - WP_HOME=http://docker.local/
    - WP_SITEURL=http://docker.local/wp
  links:
    - mariadb
  volumes:
    - ./composer:/var/composer
    - ./hhvm/:/etc/hhvm/
#    - ./my-theme:/var/www/public_html/web/app/themes/my-theme
#    - ./my-plugin:/var/www/public_html/web/app/themes/my-plugin
#    - ./environments/development.php:/var/www/public_html/config/environments/development.php #only uncomment this line if you have added a config
  expose:
    - "80"
  ports: # for xdebug
    - "9000:9000"
